CREATE TABLE Customer (
  id BIGINT AUTO_INCREMENT NOT NULL,
   FIRST_NAME VARCHAR(255) NOT NULL,
   LAST_NAME VARCHAR(255) NOT NULL,
   CPF VARCHAR(255) NOT NULL,
   INCOME DECIMAL NOT NULL,
   EMAIL VARCHAR(255) NOT NULL,
   PASSWORD VARCHAR(255) NOT NULL,
   ZIP_CODE VARCHAR(255) NOT NULL,
   STREET VARCHAR(255) NOT NULL,
   CONSTRAINT pk_customer PRIMARY KEY (id)
);

ALTER TABLE Customer ADD CONSTRAINT uc_customer_cpf UNIQUE (cpf);

ALTER TABLE Customer ADD CONSTRAINT uc_customer_email UNIQUE (email);