spring:
  datasource:
    url: jdbc:h2:mem:db_credit_request_system
    username: vitor
    password: 123456
  jpa:
    show-sql: true
    properties:
        hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
